#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — 開通 Google 登入。這一支只帶路與驗證，不經手任何密鑰：
# Client Secret 從 Google Cloud 直接貼進 Supabase 後台，不落地到這台電腦上。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REF="psuchtzacdppdpltpglg"
SB="https://${REF}.supabase.co"
ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdWNodHphY2RwcGRwbHRwZ2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg5NjA5MTEsImV4cCI6MjEwNDUzNjkxMX0.BOjc9PB7iieZsfE07ia18Y0o3VDwmOgDFTQheeN-ezc"
CALLBACK="${SB}/auth/v1/callback"
SITE="https://we-do-stuff-tw.github.io/11-up-and-down/"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# copy TEXT LABEL — 塞進剪貼簿，省得對著螢幕手打一長串網址
copy() {
  local text="$1" label="$2"
  if   command -v pbcopy    >/dev/null 2>&1; then printf '%s' "$text" | pbcopy
  elif command -v wl-copy   >/dev/null 2>&1; then printf '%s' "$text" | wl-copy
  elif command -v xclip     >/dev/null 2>&1; then printf '%s' "$text" | xclip -selection clipboard
  elif command -v clip.exe  >/dev/null 2>&1; then printf '%s' "$text" | clip.exe
  else note "（沒有剪貼簿工具，請自己複製）"; return 0; fi
  printf '  %s✎ 已複製%s %s\n' "$GREEN" "$RESET" "$label"
}

# google_on — Google provider 開了沒。回傳 0＝開了
google_on() {
  curl -fsS --max-time 12 "${SB}/auth/v1/settings" -H "apikey: ${ANON}" 2>/dev/null \
    | grep -q '"google"[[:space:]]*:[[:space:]]*true'
}

# results_exists — 戰績表建好了沒。RLS 擋著讀不到資料，但「表不存在」跟「讀不到」的回應不一樣
results_exists() {
  local body
  body=$(curl -fsS --max-time 12 "${SB}/rest/v1/results?select=id&limit=1" \
    -H "apikey: ${ANON}" -H "Authorization: Bearer ${ANON}" 2>/dev/null) || return 1
  [[ "$body" != *"Could not find the table"* && "$body" != *"does not exist"* ]]
}

banner "11 Up & Down — 開通 Google 登入"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — OAuth 同意畫面"
say "Google 要先知道「這個 app 是誰、跟使用者要什麼」，才准你建用戶端。"
say "同意畫面沒設好的話，下一步那個「建立用戶端」按鈕會是灰的。"
printf '\n'
open_url "https://console.cloud.google.com/auth/overview"
step "左上角先確認專案是你要用的那個（沒有就開一個新的，名字隨意）。"
step "「開始使用」／Get started：應用程式名稱填「11 Up & Down」，支援電子郵件選你自己。"
step "目標對象 Audience 選「外部 External」。"
step "聯絡資訊填你的 email，然後同意條款、建立。"
printf '\n'
note "如果你已經設過同意畫面，這一步跳過就好。"
pause "設好了？按 Enter 繼續"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — 建立 OAuth 用戶端 ID"
say "這一步產生一組 Client ID 與 Client Secret，等一下貼進 Supabase。"
printf '\n'
say "${BOLD}重新導向 URI 要填的就是這一行${RESET}（已經放進剪貼簿）："
printf '\n    %s%s%s\n\n' "$BOLD" "$CALLBACK" "$RESET"
copy "$CALLBACK" "重新導向 URI"
pause "先把它貼到記事本或直接留在剪貼簿，按 Enter 開 Google Cloud"
open_url "https://console.cloud.google.com/auth/clients/create"
step "應用程式類型：選「網頁應用程式 Web application」。"
step "名稱：11 Up & Down（自己看的，隨意）。"
step "「已授權的重新導向 URI」→ 新增 URI → 貼上剛剛那一行。"
warn "只需要「重新導向 URI」那一欄。上面的「JavaScript 來源」不用填。"
step "建立。畫面會跳出 Client ID 與 Client Secret —— ${BOLD}先不要關掉那個視窗${RESET}。"
printf '\n'
pause "兩個值都拿到了？按 Enter 繼續"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase — 打開 Google 開關"
say "把剛剛那兩個值貼進 Supabase。這一支不經手它們，你從瀏覽器直接貼到瀏覽器。"
printf '\n'
open_url "https://supabase.com/dashboard/project/${REF}/auth/providers"
step "在 provider 清單裡找到 Google，展開它。"
step "把「Enable Sign in with Google」打開。"
step "Client IDs 貼 Google 給的 Client ID。"
step "Client Secret 貼 Google 給的 Client Secret。"
step "Save。"
printf '\n'
pause "存好了？按 Enter，我來確認 Supabase 那邊真的開了"
printf '\n'
if google_on; then
  printf '  %s✓ 確認：Google provider 已開通%s\n' "$GREEN" "$RESET"
else
  warn "還是關的（/auth/v1/settings 回 \"google\": false）"
  note "常見原因：忘了按 Save、或存的是另一個專案。"
  note "改好之後可以重跑這支，或直接繼續——最後一關會再確認一次。"
  pause "按 Enter 繼續"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase — 允許轉回哪裡"
say "登入完 Google 會把人送回你的網站。Supabase 只肯送回白名單上的網址。"
say "沒設好的話：登入會成功，但人會被丟回首頁而不是原本那一頁。"
printf '\n'
open_url "https://supabase.com/dashboard/project/${REF}/auth/url-configuration"
say "${BOLD}Site URL${RESET} 填（已複製）："
printf '\n    %s%s%s\n\n' "$BOLD" "$SITE" "$RESET"
copy "$SITE" "Site URL"
pause "貼好 Site URL 了？按 Enter 拿下一個要貼的"
printf '\n'
say "${BOLD}Redirect URLs${RESET} 按「Add URL」加這一行（已複製）："
printf '\n    %s%s**%s\n\n' "$BOLD" "$SITE" "$RESET"
copy "${SITE}**" "Redirect URL"
note "本機開發如果也要能登入，再加一行 http://localhost:*/**"
step "Save changes。"
printf '\n'
pause "存好了？按 Enter，我來試打一次登入的入口"
printf '\n'
LOC=$(curl -fsS --max-time 12 -o /dev/null -w '%{redirect_url}' \
  "${SB}/auth/v1/authorize?provider=google&redirect_to=$(printf '%s' "$SITE" | sed 's|:|%3A|g; s|/|%2F|g')" 2>/dev/null || true)
if [[ "$LOC" == *"accounts.google.com"* ]]; then
  printf '  %s✓ 確認：登入入口已經會把人送去 Google%s\n' "$GREEN" "$RESET"
elif [[ -n "$LOC" ]]; then
  warn "入口沒送去 Google，而是送去：$LOC"
  note "通常表示 Redirect URLs 還沒存到，或 Google provider 還沒開。"
else
  warn "入口還沒通（多半是 Google provider 還沒開）。"
fi
pause "按 Enter 繼續"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Supabase — 建表（戰績與帳號欄位）"
say "players 要多幾欄放帳號 id 與頭像，另外新增一張 results 存每一場的戰績。"
say "SQL 已經寫好在 supabase/migrations/0004_auth.sql，整份放進剪貼簿了。"
printf '\n'
if [[ -f "${REPO_ROOT}/supabase/migrations/0004_auth.sql" ]]; then
  copy "$(cat "${REPO_ROOT}/supabase/migrations/0004_auth.sql")" "0004_auth.sql 全文"
else
  warn "找不到 supabase/migrations/0004_auth.sql（這支要在 repo 裡跑）"
fi
open_url "https://supabase.com/dashboard/project/${REF}/sql/new"
step "在編輯器裡貼上（Cmd-V），按 Run。"
step "跑完應該是 Success，沒有紅字。"
printf '\n'
note "這份 SQL 是可以重跑的（都有 if not exists），跑第二次不會壞。"
pause "跑完了？按 Enter，我來確認表真的在了"
printf '\n'
if results_exists; then
  printf '  %s✓ 確認：results 表已存在%s\n' "$GREEN" "$RESET"
else
  warn "還沒看到 results 表——SQL 可能沒跑成功，或跑在別的專案上。"
  pause "按 Enter 繼續"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "切換上線"
say "前面五關是「準備好」，這一關才是真的切過去。"
printf '\n'
READY=1
google_on      || { warn "Google provider 還沒開"; READY=0; }
results_exists || { warn "results 表還沒建"; READY=0; }
if (( READY )); then
  printf '  %s✓ 兩項前置都到位了%s\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "前置沒到位就切過去，線上會變成誰都進不來。建議先補完再回來跑這一關。"
fi
printf '\n'
say "切換要同時做兩件事，缺一線上就會壞："
step "把新的牌局伺服器推上 Supabase（它只認登入憑證了）"
step "把 docs/ push 上 GitHub Pages（舊的那份還在送 anon key）"
printf '\n'
note "  npx supabase functions deploy game --project-ref ${REF}"
note "  git push origin \$(git -C \"${REPO_ROOT}\" rev-parse --abbrev-ref HEAD)"
printf '\n'
if confirm "現在就切過去？（會影響線上的玩家）"; then
  printf '\n'
  say "推 edge function…"
  ( cd "$REPO_ROOT" && npx supabase functions deploy game --project-ref "$REF" ) \
    || { warn "deploy 失敗，先別 push——線上維持舊版比較安全"; exit 1; }
  printf '\n'
  BRANCH=$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)
  say "push ${BRANCH}…"
  git -C "$REPO_ROOT" push origin "$BRANCH" \
    || warn "push 失敗——伺服器已經是新版，線上網頁還是舊的，趕快處理"
  printf '\n'
  printf '  %s✓ 切換完成%s\n' "$GREEN" "$RESET"
  note "開一次 ${SITE} 確認登入頁出得來。"
else
  SKIPPED+=("切換上線：npx supabase functions deploy game --project-ref ${REF}")
  SKIPPED+=("切換上線：git push（docs/ 要跟 function 一起上）")
  note "沒切。準備好了再跑一次這支，前五關按 Enter 快速帶過即可。"
fi

finish
